version: '3.8'
services:
    bot:
        build: .
        restart: always
        stop_signal: SIGINT
        network_mode: host
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            SHOP_NAME: ${SHOP_NAME}
            PROTOCOLS: ${PROTOCOLS}
            TEST_PERIOD: ${TEST_PERIOD}
            TEST_PERIOD_DAYS: ${TEST_PERIOD_DAYS}
            ABOUT: ${ABOUT}
            RULES_LINK: ${RULES_LINK}
            SUPPORT_LINK: ${SUPPORT_LINK}
            SUPPORT_URL: ${SUPPORT_URL}
            SERVICE_NAME: ${SERVICE_NAME}
            SERVICE_URL: ${SERVICE_URL}
            START_TEXT: ${START_TEXT}
            FAQ_ABOUT_TEXT: ${FAQ_ABOUT_TEXT}
            CLIENT_NAME: ${CLIENT_NAME}
            CLIENT_IOS_NAME: ${CLIENT_IOS_NAME}
            CLIENT_IOS_URL: ${CLIENT_IOS_URL}
            CLIENT_ANDROID_NAME: ${CLIENT_ANDROID_NAME}
            CLIENT_ANDROID_URL: ${CLIENT_ANDROID_URL}
            CLIENT_ANDROID_ALT_NAME: ${CLIENT_ANDROID_ALT_NAME}
            CLIENT_ANDROID_ALT_URL: ${CLIENT_ANDROID_ALT_URL}
            CLIENT_WINDOWS_NAME: ${CLIENT_WINDOWS_NAME}
            CLIENT_WINDOWS_URL: ${CLIENT_WINDOWS_URL}
            CLIENT_LINUX_NAME: ${CLIENT_LINUX_NAME}
            CLIENT_LINUX_URL: ${CLIENT_LINUX_URL}
            CLIENT_SUBSCRIPTION_URL_SCHEME: ${CLIENT_SUBSCRIPTION_URL_SCHEME}
            CLIENT_ROUTING_URL_SCHEME: ${CLIENT_ROUTING_URL_SCHEME}
            CLIENT_ROUTING_DEFAULT_NAME: ${CLIENT_ROUTING_DEFAULT_NAME}
            CLIENT_ROUTING_DEFAULT_BASE64: ${CLIENT_ROUTING_DEFAULT_BASE64}
            FAQ_PRIVACY_URL: ${FAQ_PRIVACY_URL}
            FAQ_PRIVACY_ENABLED: ${FAQ_PRIVACY_ENABLED}
            FAQ_TERMS_URL: ${FAQ_TERMS_URL}
            FAQ_TERMS_ENABLED: ${FAQ_TERMS_ENABLED}
            FAQ_RULES_URL: ${FAQ_RULES_URL}
            FAQ_RULES_ENABLED: ${FAQ_RULES_ENABLED}
            FAQ_OFFER_URL: ${FAQ_OFFER_URL}
            FAQ_OFFER_ENABLED: ${FAQ_OFFER_ENABLED}
            START_IMAGE_ENABLED: ${START_IMAGE_ENABLED}
            START_IMAGE_PATH: ${START_IMAGE_PATH}
            SUBSCRIPTION_IMAGE_ENABLED: ${SUBSCRIPTION_IMAGE_ENABLED}
            SUBSCRIPTION_IMAGE_PATH: ${SUBSCRIPTION_IMAGE_PATH}
            INSTRUCTIONS_IMAGE_ENABLED: ${INSTRUCTIONS_IMAGE_ENABLED}
            INSTRUCTIONS_IMAGE_PATH: ${INSTRUCTIONS_IMAGE_PATH}
            FAQ_IMAGE_ENABLED: ${FAQ_IMAGE_ENABLED}
            FAQ_IMAGE_PATH: ${FAQ_IMAGE_PATH}
            SUPPORT_IMAGE_ENABLED: ${SUPPORT_IMAGE_ENABLED}
            SUPPORT_IMAGE_PATH: ${SUPPORT_IMAGE_PATH}
            HAPP_IOS_URL: ${HAPP_IOS_URL}
            HAPP_ANDROID_PLAY_URL: ${HAPP_ANDROID_PLAY_URL}
            HAPP_ANDROID_APK_URL: ${HAPP_ANDROID_APK_URL}
            HAPP_WINDOWS_URL: ${HAPP_WINDOWS_URL}
            HAPP_LINUX_URL: ${HAPP_LINUX_URL}
            YOOKASSA_TOKEN: ${YOOKASSA_TOKEN}
            YOOKASSA_SHOPID: ${YOOKASSA_SHOPID}
            EMAIL: ${EMAIL}
            CRYPTO_TOKEN: ${CRYPTO_TOKEN}
            MERCHANT_UUID: ${MERCHANT_UUID}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_ADDRESS: ${DB_ADDRESS}
            DB_PORT: ${DB_PORT}
            PANEL_HOST: ${PANEL_HOST}
            PANEL_GLOBAL: ${PANEL_GLOBAL}
            PANEL_USER: ${PANEL_USER}
            PANEL_PASS: ${PANEL_PASS}
            WEBHOOK_URL: ${WEBHOOK_URL}
            WEBHOOK_PORT: ${WEBHOOK_PORT}
            RENEW_NOTIFICATION_TIME: ${RENEW_NOTIFICATION_TIME}
            TG_INFO_CHANEL: ${TG_INFO_CHANEL}
            STARS_PAYMENT_ENABLED: ${STARS_PAYMENT_ENABLED}
            PAY_SBER_URL: ${PAY_SBER_URL}
            PAY_TBANK_URL: ${PAY_TBANK_URL}
            ADMIN_IDS: ${ADMIN_IDS}
            PROTOCOLS_CONFIG: ${PROTOCOLS_CONFIG}
            EXPIRED_NOTIFICATION_TIME: ${EXPIRED_NOTIFICATION_TIME}
        volumes:
            - "./goods.json:/app/goods.json:ro"
            - "./protocols.json:/app/protocols.json:ro"
            - "./locales:/app/locales"
        depends_on:
            db:
                condition: service_healthy
    db:
        image: mariadb:lts
        restart: always
        ports:
          - ${DB_PORT}:3306
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASS}
        volumes:
            - "mysql-data:/var/lib/mysql"
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            start_interval: 3s
            interval: 10s
            timeout: 5s
            retries: 3
volumes:
  mysql-data:
