import os

from aiogram import Bot, Dispatcher

config = {
    'BOT_TOKEN': os.environ.get('BOT_TOKEN'),
    'SHOP_NAME': os.environ.get('SHOP_NAME'),
    'PROTOCOLS': os.environ.get('PROTOCOLS', 'vless').split(),
    'PROTOCOLS_CONFIG': os.environ.get('PROTOCOLS_CONFIG', 'protocols.json'),
    'TEST_PERIOD': os.environ.get('TEST_PERIOD', 'false').lower() == 'true',
    'TEST_PERIOD_DAYS': int(os.environ.get('TEST_PERIOD_DAYS', os.environ.get('PERIOD_LIMIT', 5))),
    'ABOUT': os.environ.get('ABOUT'),
    'START_TEXT': os.environ.get('START_TEXT'),
    'FAQ_ABOUT_TEXT': os.environ.get('FAQ_ABOUT_TEXT'),
    'RULES_LINK': os.environ.get('RULES_LINK'),
    'SUPPORT_URL': os.environ.get('SUPPORT_URL', os.environ.get('SUPPORT_LINK', '')),
    'SUPPORT_LINK': os.environ.get('SUPPORT_LINK'),

    'SERVICE_NAME': os.environ.get('SERVICE_NAME', os.environ.get('SHOP_NAME', 'Swiftless Service')),
    'SERVICE_URL': os.environ.get('SERVICE_URL', ''),
    'CLIENT_NAME': os.environ.get('CLIENT_NAME', 'HAPP'),
    'CLIENT_IOS_NAME': os.environ.get('CLIENT_NAME', os.environ.get('CLIENT_IOS_NAME', 'HAPP')),
    'CLIENT_IOS_URL': os.environ.get('CLIENT_IOS_URL', os.environ.get('HAPP_IOS_URL', 'https://apps.apple.com/ru/app/happ-proxy-utility-plus/id6746188973')),
    'CLIENT_ANDROID_NAME': os.environ.get('CLIENT_NAME', os.environ.get('CLIENT_ANDROID_NAME', 'HAPP')),
    'CLIENT_ANDROID_URL': os.environ.get('CLIENT_ANDROID_URL', os.environ.get('HAPP_ANDROID_PLAY_URL', 'https://play.google.com/store/apps/details?id=com.happproxy')),
    'CLIENT_ANDROID_ALT_NAME': os.environ.get('CLIENT_NAME', os.environ.get('CLIENT_ANDROID_ALT_NAME', 'HAPP')),
    'CLIENT_ANDROID_ALT_URL': os.environ.get('CLIENT_ANDROID_ALT_URL', os.environ.get('HAPP_ANDROID_APK_URL', 'https://github.com/Happ-proxy/happ-android/releases/latest/download/Happ.apk')),
    'CLIENT_WINDOWS_NAME': os.environ.get('CLIENT_NAME', os.environ.get('CLIENT_WINDOWS_NAME', 'HAPP')),
    'CLIENT_WINDOWS_URL': os.environ.get('CLIENT_WINDOWS_URL', os.environ.get('HAPP_WINDOWS_URL', 'https://github.com/Happ-proxy/happ-desktop/releases/latest/download/setup-Happ.x86.exe')),
    'CLIENT_LINUX_NAME': os.environ.get('CLIENT_NAME', os.environ.get('CLIENT_LINUX_NAME', 'HAPP')),
    'CLIENT_LINUX_URL': os.environ.get('CLIENT_LINUX_URL', os.environ.get('HAPP_LINUX_URL', 'https://github.com/Happ-proxy/happ-desktop/releases/')),
    'CLIENT_SUBSCRIPTION_URL_SCHEME': os.environ.get('CLIENT_SUBSCRIPTION_URL_SCHEME', 'happ://add{url}'),
    'CLIENT_ROUTING_URL_SCHEME': os.environ.get('CLIENT_ROUTING_URL_SCHEME', 'happ://routing/add{base64}'),
    'CLIENT_ROUTING_DEFAULT_NAME': os.environ.get('CLIENT_ROUTING_DEFAULT_NAME', 'RoscomVPN'),
    'CLIENT_ROUTING_DEFAULT_BASE64': os.environ.get('CLIENT_ROUTING_DEFAULT_BASE64', 'ewogICAgIkJsb2NrSXAiOiBbCiAgICBdLAogICAgIkJsb2NrU2l0ZXMiOiBbCiAgICAgICAgImdlb3NpdGU6d2luLXNweSIsCiAgICAgICAgImdlb3NpdGU6dG9ycmVudCIsCiAgICAgICAgImdlb3NpdGU6Y2F0ZWdvcnktYWRzIgogICAgXSwKICAgICJEaXJlY3RJcCI6IFsKICAgICAgICAiZ2VvaXA6cHJpdmF0ZSIsCiAgICAgICAgImdlb2lwOmRpcmVjdCIKICAgIF0sCiAgICAiRGlyZWN0U2l0ZXMiOiBbCiAgICAgICAgImdlb3NpdGU6cHJpdmF0ZSIsCiAgICAgICAgImdlb3NpdGU6Y2F0ZWdvcnktcnUiLAogICAgICAgICJnZW9zaXRlOndoaXRlbGlzdCIsCiAgICAgICAgImdlb3NpdGU6bWljcm9zb2Z0IiwKICAgICAgICAiZ2Vvc2l0ZTphcHBsZSIsCiAgICAgICAgImdlb3NpdGU6Z29vZ2xlLXBsYXkiLAogICAgICAgICJnZW9zaXRlOmVwaWNnYW1lcyIsCiAgICAgICAgImdlb3NpdGU6cmlvdCIsCiAgICAgICAgImdlb3NpdGU6ZXNjYXBlZnJvbXRhcmtvdiIsCiAgICAgICAgImdlb3NpdGU6c3RlYW0iLAogICAgICAgICJnZW9zaXRlOm9yaWdpbiIsCiAgICAgICAgImdlb3NpdGU6dHdpdGNoIiwKICAgICAgICAiZ2Vvc2l0ZTpwaW50ZXJlc3QiLAogICAgICAgICJnZW9zaXRlOmZhY2VpdCIKICAgIF0sCiAgICAiRG5zSG9zdHMiOiB7CiAgICAgICAgImxrZmwyLm5hbG9nLnJ1IjogIjIxMy4yNC42NC4xNzUiLAogICAgICAgICJsa25wZC5uYWxvZy5ydSI6ICIyMTMuMjQuNjQuMTgxIgogICAgfSwKICAgICJEb21haW5TdHJhdGVneSI6ICJJUElmTm9uTWF0Y2giLAogICAgIkRvbWVzdGljRE5TRG9tYWluIjogImh0dHBzOi8vNzcuODguOC44L2Rucy1xdWVyeSIsCiAgICAiRG9tZXN0aWNETlNJUCI6ICI3Ny44OC44LjgiLAogICAgIkRvbWVzdGljRE5TVHlwZSI6ICJEb0giLAogICAgIkZha2VETlMiOiAiZmFsc2UiLAogICAgIkdlb2lwdXJsIjogImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9naC9oeWRyYXBvbmlxdWUvcm9zY29tdnBuLWdlb2lwQDIwMjYwMzE5MDY1MS9yZWxlYXNlL2dlb2lwLmRhdCIsCiAgICAiR2Vvc2l0ZXVybCI6ICJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvZ2gvaHlkcmFwb25pcXVlL3Jvc2NvbXZwbi1nZW9zaXRlQDIwMjYwMzE4MTkwMS9yZWxlYXNlL2dlb3NpdGUuZGF0IiwKICAgICJHbG9iYWxQcm94eSI6ICJ0cnVlIiwKICAgICJMYXN0VXBkYXRlZCI6IDE3NzM5MDY0MDIsCiAgICAiTmFtZSI6ICJSb3Njb21WUE4iLAogICAgIlByb3h5SXAiOiBbCiAgICBdLAogICAgIlByb3h5U2l0ZXMiOiBbCiAgICAgICAgImdlb3NpdGU6Z2l0aHViIiwKICAgICAgICAiZ2Vvc2l0ZTp0d2l0Y2gtYWRzIiwKICAgICAgICAiZ2Vvc2l0ZTp5b3V0dWJlIiwKICAgICAgICAiZ2Vvc2l0ZTp0ZWxlZ3JhbSIKICAgIF0sCiAgICAiUmVtb3RlRE5TRG9tYWluIjogImh0dHBzOi8vOC44LjguOC9kbnMtcXVlcnkiLAogICAgIlJlbW90ZUROU0lQIjogIjguOC44LjgiLAogICAgIlJlbW90ZUROU1R5cGUiOiAiRG9IIiwKICAgICJSb3V0ZU9yZGVyIjogImJsb2NrLXByb3h5LWRpcmVjdCIKfQo='),
    'DB_URL': f"mysql+asyncmy://{os.environ.get('DB_USER')}:{os.environ.get('DB_PASS')}@{os.environ.get('DB_ADDRESS')}:{os.environ.get('DB_PORT')}/{os.environ.get('DB_NAME')}",
    'YOOKASSA_TOKEN': os.environ.get('YOOKASSA_TOKEN'),
    'YOOKASSA_SHOPID': os.environ.get('YOOKASSA_SHOPID'),
    'EMAIL': os.environ.get('EMAIL'),
    'CRYPTO_TOKEN': os.environ.get('CRYPTO_TOKEN'),
    'MERCHANT_UUID': os.environ.get('MERCHANT_UUID'),
    'PANEL_HOST': os.environ.get('PANEL_HOST'),
    'PANEL_GLOBAL': os.environ.get('PANEL_GLOBAL'),
    'PANEL_USER': os.environ.get('PANEL_USER'),
    'PANEL_PASS': os.environ.get('PANEL_PASS'),
    'WEBHOOK_URL': os.environ.get('WEBHOOK_URL'),
    'WEBHOOK_PORT': int(os.environ.get('WEBHOOK_PORT')),
    'RENEW_NOTIFICATION_TIME': os.environ.get('RENEW_NOTIFICATION_TIME'),
    'TG_INFO_CHANEL': os.environ.get('TG_INFO_CHANEL'),
    'STARS_PAYMENT_ENABLED': os.environ.get('STARS_PAYMENT_ENABLED', 'false').lower() == 'true',
    'EXPIRED_NOTIFICATION_TIME': os.environ.get('EXPIRED_NOTIFICATION_TIME'),
    'PAY_SBER_URL': os.environ.get('PAY_SBER_URL'),
    'PAY_TBANK_URL': os.environ.get('PAY_TBANK_URL'),
    'ADMIN_IDS': [int(x) for x in os.environ.get('ADMIN_IDS', '').split(',') if x.strip().isdigit()],
    'START_IMAGE_ENABLED': os.environ.get('START_IMAGE_ENABLED', 'false').lower() == 'true',
    'START_IMAGE_PATH': os.environ.get('START_IMAGE_PATH'),
    'SUBSCRIPTION_IMAGE_ENABLED': os.environ.get('SUBSCRIPTION_IMAGE_ENABLED', 'false').lower() == 'true',
    'SUBSCRIPTION_IMAGE_PATH': os.environ.get('SUBSCRIPTION_IMAGE_PATH'),
    'INSTRUCTIONS_IMAGE_ENABLED': os.environ.get('INSTRUCTIONS_IMAGE_ENABLED', 'false').lower() == 'true',
    'INSTRUCTIONS_IMAGE_PATH': os.environ.get('INSTRUCTIONS_IMAGE_PATH'),
    'FAQ_IMAGE_ENABLED': os.environ.get('FAQ_IMAGE_ENABLED', 'false').lower() == 'true',
    'FAQ_IMAGE_PATH': os.environ.get('FAQ_IMAGE_PATH'),
    'SUPPORT_IMAGE_ENABLED': os.environ.get('SUPPORT_IMAGE_ENABLED', 'false').lower() == 'true',
    'SUPPORT_IMAGE_PATH': os.environ.get('SUPPORT_IMAGE_PATH'),
    'FAQ_PRIVACY_URL': os.environ.get('FAQ_PRIVACY_URL', ''),
    'FAQ_PRIVACY_ENABLED': os.environ.get('FAQ_PRIVACY_ENABLED', 'false').lower() == 'true',
    'FAQ_TERMS_URL': os.environ.get('FAQ_TERMS_URL', ''),
    'FAQ_TERMS_ENABLED': os.environ.get('FAQ_TERMS_ENABLED', 'false').lower() == 'true',
    'FAQ_RULES_URL': os.environ.get('FAQ_RULES_URL', ''),
    'FAQ_RULES_ENABLED': os.environ.get('FAQ_RULES_ENABLED', 'false').lower() == 'true',
    'FAQ_OFFER_URL': os.environ.get('FAQ_OFFER_URL', ''),
    'FAQ_OFFER_ENABLED': os.environ.get('FAQ_OFFER_ENABLED', 'false').lower() == 'true',
    'HAPP_IOS_URL': os.environ.get('HAPP_IOS_URL', 'https://apps.apple.com/ru/app/happ-proxy-utility-plus/id6746188973'),
    'HAPP_ANDROID_PLAY_URL': os.environ.get('HAPP_ANDROID_PLAY_URL', 'https://play.google.com/store/apps/details?id=com.happproxy'),
    'HAPP_ANDROID_APK_URL': os.environ.get('HAPP_ANDROID_APK_URL', 'https://github.com/Happ-proxy/happ-android/releases/latest/download/Happ.apk'),
    'HAPP_WINDOWS_URL': os.environ.get('HAPP_WINDOWS_URL', 'https://github.com/Happ-proxy/happ-desktop/releases/latest/download/setup-Happ.x86.exe'),
    'HAPP_LINUX_URL': os.environ.get('HAPP_LINUX_URL', 'https://github.com/Happ-proxy/happ-desktop/releases/'),
}

bot: Bot = None
storage = None
dp: Dispatcher = None
